# Generated by Django 2.0.5 on 2018-05-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='terreno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Terreno'),
        ),
        migrations.AddField(
            model_name='humedad',
            name='depto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Departamento'),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='cantidad_fertilizante',
            field=models.FloatField(null=True),
        ),
    ]
