# Generated by Django 2.0.5 on 2018-05-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180524_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='terreno',
        ),
        migrations.AddField(
            model_name='terreno',
            name='depto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Departamento'),
        ),
    ]
